name: build Debian image
on:
  push:
    branches: [master, debian-buster]
jobs:
  build_and_publish:
    name: Build a Debian image and makes a release out of it.
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y simple-cdd xorriso debian-archive-keyring

      - name: Build buster image for APU
        run: ./build apu64 buster

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #tag_name: ${{ github.ref }}
          tag_name: ${{ github.sha }}
          #release_name: Release ${{ github.ref }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url }}
          asset_path: ./images/debian-10-amd64-CD-1.iso
          asset_name: debian-10-amd64-CD-1.iso
          asset_content_type: application/octet-stream
